# Generated by Django 3.2.5 on 2021-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='simulationtype',
            field=models.CharField(default='', max_length=20, verbose_name='simulationtype'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'uid', 'simulationtype')},
        ),
    ]
